### ISSUE TITLE
KeyError: 'CCND1' at the end of Process_Assembled_BAM.py (trinity workflow)

### ISSUE THREAD

**Issue by bryce-turner** [tgen/phoenix#422]
Tail of error log:
```
cigar=133M384H
     h in 7 m index 3 s index-1
     m first=133
    Traceback (most recent call last):
      File "/home/tgenjetstream/jetstream_pipelines/phoenix-v1_1_2/required_scripts/Process_Assembled_BAM_eb25fca.py", line 1103, in <module>
        summ_table = gen_summ_table(filt_table, results_table, min_reads, window_size, sample_name)
      File "/home/tgenjetstream/jetstream_pipelines/phoenix-v1_1_2/required_scripts/Process_Assembled_BAM_eb25fca.py", line 998, in gen_summ_table
        ccnd1_call = check_gene_call(filt_table, "CCND1", nreads, min_con_len)
      File "/home/tgenjetstream/jetstream_pipelines/phoenix-v1_1_2/required_scripts/Process_Assembled_BAM_eb25fca.py", line 756, in check_gene_call
        source = ig_dict[gene_tmp]
    KeyError: 'CCND1'
```

**Comment by bryce-turner** [comment]
This should be resolved with the latest updates to the processing script in commit 045e6b1. This wasn't an intentional fix, but side effect of case statement changes.
